baseurl = "/"
languageCode = "en-us"
title = "Joshua M. Rosenberg"
theme = "hugo-xmin"
googleAnalytics = "UA-43032207-1"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"
paginate = 5
math = true

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "CV"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Research"
    url = "/research/"
    weight = 3
[[menu.main]]
    name = "Teaching"
    url = "/teaching/"
    weight = 4
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 5
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 6

[params]
    description = "Joshua M. Rosenberg's Homepage"
    footer = "&copy; [Joshua M. Rosenberg](https://joshuamrosenberg.com) 2015 -- 2018 | [Google Scholar](https://scholar.google.com/citations?user=nxVowRQAAAAJ&hl=en) | [ResearchGate](https://www.researchgate.net/profile/Joshua_Rosenberg2) | [Github](https://github.com/jrosen48) | [Twitter](https://twitter.com/jrosenberg6432)"